# Generated by Django 6.0.2 on 2026-04-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('stat', models.CharField(max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_bets', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('total_pnl', models.FloatField(default=0.0)),
                ('roi', models.FloatField(default=0.0, help_text='Return on investment as a percentage')),
            ],
            options={
                'indexes': [models.Index(fields=['player_name', 'stat', 'date_from', 'date_to'], name='nba_betting_player__93f2f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('opponent', models.CharField(max_length=10)),
                ('actual', models.FloatField()),
                ('line', models.FloatField()),
                ('prob_over', models.FloatField()),
                ('predicted_over', models.BooleanField()),
                ('correct', models.BooleanField()),
                ('pnl', models.FloatField(help_text='+1.0 if correct, -1.1 if wrong (simulates -110 odds)')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='nba_betting.backtestrun')),
            ],
            options={
                'ordering': ['game_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateField(db_index=True)),
                ('opponent_abbr', models.CharField(max_length=10)),
                ('is_home', models.BooleanField()),
                ('stat', models.CharField(choices=[('pts', 'Points'), ('reb', 'Rebounds'), ('ast', 'Assists')], max_length=10)),
                ('line', models.FloatField(help_text='L5 rolling average used as the model line')),
                ('prob_over', models.FloatField()),
                ('projection', models.FloatField()),
                ('edge', models.CharField(max_length=10)),
                ('model_version', models.CharField(default='xgb_v1', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_betting.player')),
            ],
            options={
                'ordering': ['-prob_over'],
                'unique_together': {('pick_date', 'player', 'stat')},
            },
        ),
    ]
