# Generated by Django 5.2 on 2026-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_betting', '0003_add_error_to_backtest_result'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backtestrun',
            name='nba_betting_player__93f2f2_idx',
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='model',
            field=models.CharField(choices=[('xgb', 'XGBoost'), ('rf', 'Random Forest'), ('lr', 'Linear Regression'), ('naive', 'Naive (Season Avg)')], default='xgb', max_length=20),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['player_name', 'stat', 'model', 'date_from', 'date_to'], name='nba_betting_player__0ab765_idx'),
        ),
    ]
